version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./app:/app
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
