version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./application:/app
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./application:/app
    networks:
      - code-network

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - ./mysql/.env
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
